version: '3.9'
services:
  
  test:
    image: drink
    container_name: test
    restart: always
    ports:
      - 6000:6000


  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass123
#      - MONGO_INITDB_DATABASE=drinks

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass123@mongodb:27017/