---
plugin: aws_ec2
#aws cli profile (profile name is set while the creation of the .aws dic)
boto_profile: aws_profile
regions:
  - us-east-1
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
hostnames:
  - private-ip-address
# Doc. https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#options