apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drinks
  name: drinks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drinks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drinks
    spec:
      containers:
      - image: drinks
        name: drinks
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        